In [26]:
import json
import pandas as pd

In [27]:
DATA_PATH = "data/ori_pqal.json"

with open(DATA_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

type(data)

dict

In [28]:
len(data)

1000

In [29]:
list(data.keys())[:5]

['21645374', '16418930', '9488747', '17208539', '10808977']

In [30]:
first_key = list(data.keys())[0]

first_key

'21645374'

In [31]:
data[first_key]

{'QUESTION': 'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?',
 'CONTEXTS': ['Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Aponogeton madagascariensis) produces perforations in its leaves through PCD. The leaves of the plant consist of a latticework of longitudinal and transverse veins enclosing areoles. PCD occurs in the cells at the center of these areoles and progresses outwards, stopping approximately five cells from the vasculature. The role of mitochondria during PCD has been recognized in animals; however, it has been less studied during PCD in plants.',
  'The following paper elucidates the role of mitochondrial dynamics during developmentally regulated PCD in vivo in A. madagascariensis. A single areole within a window stage leaf (PCD is occurring) was divided into three areas based on the progression of PCD; cells that will not undergo PCD (NPCD), cells in early stages of PCD (EPCD), and cells in late stages of PCD (LPCD). Window stage leaves were stained with the mitochondrial dye MitoTracker Red CMXRos and examined. Mitochondrial dynamics were delineated into four categories (M1-M4) based on characteristics including distribution, motility, and membrane potential (ΔΨm). A TUNEL assay showed fragmented nDNA in a gradient over these mitochondrial stages. Chloroplasts and transvacuolar strands were also examined using live cell imaging. The possible importance of mitochondrial permeability transition pore (PTP) formation during PCD was indirectly examined via in vivo cyclosporine A (CsA) treatment. This treatment resulted in lace plant leaves with a significantly lower number of perforations compared to controls, and that displayed mitochondrial dynamics similar to that of non-PCD cells.'],
 'LABELS': ['BACKGROUND', 'RESULTS'],
 'MESHES': ['Alismataceae',
  'Apoptosis',
  'Cell Differentiation',
  'Mitochondria',
  'Plant Leaves'],
 'YEAR': '2011',
 'reasoning_required_pred': 'yes',
 'reasoning_free_pred': 'yes',
 'final_decision': 'yes',
 'LONG_ANSWER': 'Results depicted mitochondrial dynamics in vivo as PCD progresses within the lace plant, and highlight the correlation of this organelle with other organelles during developmental PCD. To the best of our knowledge, this is the first report of mitochondria and chloroplasts moving on transvacuolar strands to form a ring structure surrounding the nucleus during developmental PCD. Also, for the first time, we have shown the feasibility for the use of CsA in a whole plant system. Overall, our findings implicate the mitochondria as playing a critical and early role in developmentally regulated PCD in the lace plant.'}

In [32]:
rows = []

for question_id, item in data.items():
    row = {
        "question_id": question_id,
        "question": item.get("QUESTION", ""),
        "contexts": item.get("CONTEXTS", []),
        "labels": item.get("LABELS", []),
        "meshes": item.get("MESHES", []),
        "year": item.get("YEAR", ""),
        "reasoning_required": item.get("reasoning_required_pred", ""),
        "final_decision": item.get("final_decision", ""),
        "long_answer": item.get("LONG_ANSWER", "")
    }
    
    rows.append(row)

df = pd.DataFrame(rows)

df.head()

  question_id  ...                                        long_answer
0    21645374  ...  Results depicted mitochondrial dynamics in viv...
1    16418930  ...  Using the charts described, there was only a s...
2     9488747  ...  "Aquagenic maladies" could be a pediatric form...
3    17208539  ...  Our long-term study showed significantly bette...
4    10808977  ...  The effects of the intervention were most pron...

[5 rows x 9 columns]

In [33]:
df.shape

(1000, 9)

In [34]:
df.columns

Index(['question_id', 'question', 'contexts', 'labels', 'meshes', 'year',
       'reasoning_required', 'final_decision', 'long_answer'],
      dtype='object')

In [35]:
df.head(3)

  question_id  ...                                        long_answer
0    21645374  ...  Results depicted mitochondrial dynamics in viv...
1    16418930  ...  Using the charts described, there was only a s...
2     9488747  ...  "Aquagenic maladies" could be a pediatric form...

[3 rows x 9 columns]

In [36]:
def join_contexts(contexts):
    if isinstance(contexts, list):
        return " ".join(contexts)
    return str(contexts)

df["context_text"] = df["contexts"].apply(join_contexts)

In [37]:
df[["question", "context_text", "final_decision", "long_answer"]].head()

                                            question  ...                                        long_answer
0  Do mitochondria play a role in remodelling lac...  ...  Results depicted mitochondrial dynamics in viv...
1  Landolt C and snellen e acuity: differences in...  ...  Using the charts described, there was only a s...
2  Syncope during bathing in infants, a pediatric...  ...  "Aquagenic maladies" could be a pediatric form...
3  Are the long-term results of the transanal pul...  ...  Our long-term study showed significantly bette...
4  Can tailored interventions increase mammograph...  ...  The effects of the intervention were most pron...

[5 rows x 4 columns]

In [38]:
df["medical_text"] = (
    "Question: " + df["question"].astype(str) + "\n\n" +
    "Context: " + df["context_text"].astype(str) + "\n\n" +
    "Long answer: " + df["long_answer"].astype(str) + "\n\n" +
    "Final decision: " + df["final_decision"].astype(str)
)

In [39]:
df = df.dropna(subset=["question", "context_text"])

df = df[df["question"].str.len() > 5]
df = df[df["context_text"].str.len() > 50]

df.shape

(1000, 11)

In [41]:
df.to_csv("data/pubmedqa_clean.csv", index=False, encoding="utf-8")

print("Saved clean dataset to ../data/pubmedqa_clean.csv")

Saved clean dataset to ../data/pubmedqa_clean.csv